### ISSUE TITLE
[Proposal] Scopes with descriptions

### ISSUE THREAD

**Issue by SergioRibera** [romancitodev/simple-commits#11]
The scopes currently do not have a description, it would be good to add it so that there is a better detail when choosing a scope

It could look like this:
```toml
scopes = [
    { name = "app", description = "blablablabla" },
    { name = "lib", description = "blablablabla" },
]
```

**Comment by romancitodev** [comment]
That really makes sense!

We would implement it into the first version.

**Comment by romancitodev** [comment]
After some deep research we achieve that inquire doesn't support custom on highlight on some autocompletion, so in a future version of the CLI we are moving to [cliclack](https://github.com/fadeevab/cliclack)
